fi: line exit, trigger, mktemp

diff --git a/please b/please
--- a/please
+++ b/please
@@ -15,12 +15,12 @@ declare -A EVENTS
 FULL=`readlink -f $0` # fullpath
 PLIZ=`basename $0`    # name
 
-line() { echo -e "\e[${3:-0};$2m$1\e[0m" && [[ "$4" != "" ]] && exit $4; }
-error() { line "$1" 31 0 ${2:-}; }
-ok() { line "${1:-  Done}" 32 0 ${2:-}; }
-info() { line "$1" 33 0 ${2:-}; }
-comment() { line "$1" 30 1 ${2:-}; }
-
+line() { echo -e "\e[${3:-0};$2m$1\e[0m"; if [[ "$4" != "" ]]; then exit $4; fi }
+error() { line "$1" 31 0 $2; }
+ok() { line "${1:-  Done}" 32 0 $2; }
+info() { line "$1" 33 0 $2; }
+comment() { line "$1" 30 1 $2; }
+# info 1
 qgit() { git "$@" &>> $TMP_LOG; }
 
 # github api
@@ -198,9 +198,9 @@ publish-npm()
 # trigger event
 trigger() # $1 = event
 {
-  local EVENT="$1"  CMD="${EVENTS[$EVENT]}"
+  local CMD="${EVENTS[$1]}"
   if [[ "$CMD" != "" ]]; then
-    echo -e "$(info Running) $(ok "$EVENT")\n$(comment "> $CMD")"
+    echo -e "$(info Running) $(ok "$1")\n$(comment "> $CMD")"
     eval "CMD=\"${CMD//{/\${}\"" && eval "$CMD"
   fi
 }
@@ -208,6 +208,7 @@ trigger() # $1 = event
 GCFMT="%s (%an)"    # git commit log format
 REPO=`git config --get remote.origin.url | sed -e 's/git@github.com://;s/https:\/\/github.com\///;s/.git//'`
 
+# load events
 [[ -f ./please.json ]] && eval $(cat ./please.json | jq -r 'to_entries|map("EVENTS[\(.key)]=\"\(.value)\"")|.[]')
 
 # argv parsing
@@ -231,6 +232,7 @@ while [[ $# -gt 0 ]]; do
 done
 
 [[ $REPO ]] || error "$(pwd) is not git repo" 1
+[[ -z "$GH_AUTH_TOKEN" ]] && error "GH_AUTH_TOKEN missing" 1
 
 GPUSH=0             # git push pending
 MAJOR=${MAJOR:-0}   # bump major
@@ -239,9 +241,7 @@ VFILE=${VFILE:-0}   # create version file
 CHLOG=${CHLOG:-0}   # create changelog file
 YES=${YES:-0}       # assume yes
 
-[[ -z "$GH_AUTH_TOKEN" ]] && error "GH_AUTH_TOKEN missing" 1
-
-GH_REPO="github.com/repos/$REPO" TMP_LOG=`mktemp -p PLZ.XXXXXXXXXX`
+GH_REPO="github.com/repos/$REPO"  TMP_LOG=`mktemp -t PLZ.XXXXXXXXXX`
 ok "Repository $REPO" && info "Log file $TMP_LOG"
 
 DEPLOY_BRANCH="${DEPLOY_BRANCH:-master}"
